version: '3.1'

services:
  db:
    build: .
    container_name: devtraining-db
    restart: always
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Espelhar dados de onde o postgres salva para a máquina local
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devtraining
  dbteste:
    build: .
    container_name: teste-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devtraining
volumes:
  postgres_data: 

#.docker/dbdata